spring:
  application:
  name: bookManagement
  graphql:
    path: /graphql

server:
  port: 2193

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/bmsdb
  username: postgres
  password: kim21

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true